### ISSUE TITLE
mixpanel.track fails with Firefox 48.0.2

### ISSUE THREAD

**Issue by adadgio** [mixpanel/mixpanel-js#106]
Mixpanel events are not sent on Firefox 48.0.2 (MAC OS version). No errors are shown and the Network to  `api.mixpanel.com?data=...` does not event appear in the console.

The exact same code works on Chrome and Safari. To note as well, i'm not able to see any calls to api.mixpanel.com (i know the identify method throws them as well, but nothing. I tmight as well be an issue with the identify method).

**Comment by tdumitrescu** [comment]
Thanks for the report, we'll look into it right away. If you could send off an email to support@mixpanel.com they'll be able to help investigate whether it's something specific to your setup or the library code. Thanks.

**Comment by adadgio** [comment]
Done.

**Comment by adadgio** [comment]
The tracking was not working because history settings in Firefox were set to "Never remember history". Is that a wanted behavior ?

**Comment by tdumitrescu** [comment]
That shouldn't be the case. Out of curiosity, do you have "Use Tracking Protection in Private Windows" turned on in your Firefox privacy settings? Looks like it's enabled by default:
![screen shot 2016-09-20 at 11 18 03 am](https://cloud.githubusercontent.com/assets/855881/18683207/16e05d52-7f24-11e6-9aa3-a89e11d878ed.png)
and according to https://support.mozilla.org/en-US/kb/settings-privacy-browsing-history-do-not-track, "Using Never remember history is equivalent to always being in Firefox Private Browsing mode." Seems like that might be a reason why "Never remember history" is blocking tracking for you?

**Comment by codeincarnate** [comment]
This is still an issue and appears to be affecting Firefox in private browsing mode and also uBlock Origin in both Chrome and Firefox.
